### ISSUE TITLE
[FEAT] 웰컴 페이지

### ISSUE THREAD

**Issue by rogitun** [HanselKiosk/frontend#10]
## 설명 📓
> 이슈에 대한 설명을 작성합니다.  이슈 분류는 라벨로 표시. 

웰컴 페이지
## 체크사항 ☑️
> 이슈를 close하기 위해 필요한 조건들을 체크박스로 나열합니다. (변경된 사항들)
- [ ] 상단 안내 태그
- [ ] 하단 버튼
- [ ] 두가지 선택 버튼
- [ ] 웰컴 페이지 

## 참고자료 ⁉️
> 

https://www.notion.so/Sprint-2-004da04eff8d44f2a196f4a5bbbea625?p=9e82aef049624e31bce2cb44239bf1c8&pm=s

## 관련 논의 🧑‍🤝‍🧑
>

 더 추가할 공통 컴포넌트 있으면 체크사항에 추가 바람.

**Comment by yejipractice** [comment]
이 아저씨는 할당도 안하고 말이야

**Comment by yejipractice** [comment]
지금 develop이랑 충돌이 많네요 패키지 lock 관련해서..  
https://habitual-history.tistory.com/entry/Git-npm-package-lockjson-conflict-%EC%B6%A9%EB%8F%8C%ED%95%B4%EA%B2%B0-%EB%B0%8F-%EC%A1%B4%EC%9E%AC%EC%9D%B4%EC%9C%A0

**Comment by rogitun** [comment]
> 지금 develop이랑 충돌이 많네요 패키지 lock 관련해서.. https://habitual-history.tistory.com/entry/Git-npm-package-lockjson-conflict-%EC%B6%A9%EB%8F%8C%ED%95%B4%EA%B2%B0-%EB%B0%8F-%EC%A1%B4%EC%9E%AC%EC%9D%B4%EC%9C%A0 방안을 찾아보고 룰 하나 추가해야겠어요

수정해서 올렸어요~

**Comment by yejipractice** [comment]
오 이런 방법이..!!! 감사합니다~
